trigger:
  branches:
    include:
      - main
      - email_Service

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    echo "Installing root dependencies"
    npm ci
  displayName: 'Install root dependencies'

- script: |
    echo "Build frontend"
    npm run build --if-present
  displayName: 'Build frontend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/smartstock-frontend'
    ArtifactName: 'frontend'
    publishLocation: 'Container'
  displayName: 'Publish frontend artifact'
